name = "JessamineSciKitLearn"
uuid = "b1d08412-962e-4858-8b05-b07944b12f63"
authors = ["W. Garrett Mitchener <garrett.mitchener@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
